language: dart
sudo: false
dart:
  - dev
  - stable
  - 1.24.2
  - 1.23.0
  - 1.22.1

dart_task:
  - dartanalyzer
  - dartfmt
  - test: --platform vm
  - test: --platform firefox
  - test: --platform dartium
    install_dartium: true

matrix:
  allow_failures:
    - dart: dev
      dart_task: dartfmt

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
  directories:
    - $HOME/.pub-cache
